package com.bankproject.bank.entity.Enum;

public enum RolePermission {

    CREATE_PROFILE,
    CREATE_BRANCH,
    CREATE_ACCOUNT,
    CREATE_SERVICE,

    READ_ALL_PROFILES,
    READ_ONE_PROFILE,
    READ_ALL_BRANCHES,
    READ_ONE_BRANCH,
    READ_ALL_ACCOUNTS,
    READ_ONE_ACCOUNT,
    READ_ALL_SERVICES,
    READ_ONE_SERVICE,

    UPDATE_PROFILE,
    UPDATE_BRANCH,
    UPDATE_ACCOUNT,
    UPDATE_SERVICE,

    DELETE_PROFILE,
    DELETE_BRANCH,
    DELETE_ACCOUNT,
    DELETE_SERVICE
}
